name: Construire CacVision.exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Construire CacVision.exe
        run: |
          pyinstaller --onefile --windowed --name CacVision --icon=cacvision.ico cacvision.py

      - name: Récupérer CacVision.exe
        uses: actions/upload-artifact@v4
        with:
          name: CacVision-Windows
          path: dist/CacVision.exe
